clone:
  git:
    image: plugins/git
    path: /drone/src/gituhb.com/gocaio/Goca

pipeline:
  test:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/drone
      - GO111MODULE=on
    commands:
      - make deps
      - make test
    when:
      branch: dev
  
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/drone
      - GO111MODULE=on
    commands:
      - make deps
      - make test
      - make build
    when:
      branch: master

  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    format: markdown
    message: >
      \[DRONE] {{uppercasefirst build.status}} build for commit [{{commit.message}} ({{truncate commit.sha 10}})]({{commit.link}}) by {{commit.author}}
    when:
      status: [success, failure]

matrix:
  GO_VERSION:
    - latest