env:
  - GO111MODULE=on

language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

before_deploy:
  - ./build.sh

jobs:
  include:
    - stage: Getting dependencies
      script: go get -t -v ./...
    - stage: Running tests
      script: go test -v -race -count 1 -coverprofile=coverage.txt -covermode=atomic ./...
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GH_KEY
        skip_cleanup: true
        overwrite: true
        on:
          tags: true